### Create a new UseHotel
POST http://localhost:5000/v1/hotels/
Content-Type: application/json

{"name": "Spogmay Hotel2", 
"type":"hotel",
"city":"California",
"address":"1235 hastings st",
"distance":"500",
"title": "Best Hotel",
"desc": "Hoteell",
"cheapestPrice": 100
}

### Update Hotel
PUT http://localhost:5000/v1/hotels/630c96f619b49ba0cca1b056
Content-Type: application/json

{"name": "Intercontenintal Hotel", 
"type":"hotel",
"city":"Kabul",
"address":"Bagh bala st",
"distance":"500",
"title": "Best Hotel",
"desc": "Hoteell",
"cheapestPrice": 100
}


### Delete a Hotel
DELETE http://localhost:5000/v1/hotels/630c755e4a55a78f7588f441
Content-Type: application/json


### Get Hotels
GET http://localhost:5000/v1/hotels/
Content-Type: application/json



### Get a hotel by id
GET http://localhost:5000/v1/hotels/hotel/630c755e4a55a78f7588f441
Content-Type: application/json



### Get hotels count based on citites.
##Queries is case-sensitive
#[1,2,3]... 
GET http://localhost:5000/v1/hotels/countByCity?cities=Vancouver,Kabul,Richmond,Seatal
Content-Type: application/json



### Get hotels count based on Types.
GET http://localhost:5000/v1/hotels/countByType
Content-Type: application/json






# ------------------------------------------------------------------

### User sign up
POST http://localhost:5000/v1/auth/register
Content-Type: application/json

{"username": "noAdminUser", 
"email":"sefat3@gmail.com",
"password": "Password5%",
"phone":"12341235",
"city":"Vancouver",
"country": "Canada",
"isAdmin": false
}


### User sign in
POST http://localhost:5000/v1/auth/login
Content-Type: application/json

{"username": "user2", 
"password": "Password5"
}


### Checking User Authentication, it also wokrs without mentioning cookies.
GET http://localhost:5000/v1/users/checkauthentication
headers: Cookie: {"access_token": ""}
Content-Type: application/json



### Checking User verification.
GET http://localhost:5000/v1/users/checkuser/630c96f619b49ba0cca1b056
headers: Cookie: {"access_token": ""}
Content-Type: application/json


### Verifying is User Admin verification.
GET http://localhost:5000/v1/users/checkadmin/630c96f619b49ba0cca1b056
headers: Cookie: {"access_token": ""}
Content-Type: application/json


### Get user 
GET http://localhost:5000/v1/users/630c96f619b49ba0cca1b056
Content-Type: application/json


### Get users 
GET http://localhost:5000/v1/users/
Content-Type: application/json



### Get user 
DELETE http://localhost:5000/v1/users/630c96f619b49ba0cca1b056
Content-Type: application/json

# ------------------------------------------------------------------


### Create a new Room
POST http://localhost:5000/v1/rooms/630c755e4a55a78f7588f441
Content-Type: application/json

{
"title": "Huge room",
"desc": "Rooms available for a family",
"price":100,
"maxPeople":2,
"roomNumbers": [{"number":102}, {"number":102}]
}


### Get a Room
GET http://localhost:5000/v1/rooms/630d9a85ad5759b952860df2/
Content-Type: application/json


### Get Rooms
GET http://localhost:5000/v1/rooms/
Content-Type: application/json


### Delete a Room
DELETE http://localhost:5000/v1/rooms/630da0391ec1bd093f795b9c/630c755e4a55a78f7588f441
Content-Type: application/json