### Create a new Flight
POST http://localhost:8000/v1/flights/
Content-Type: application/json

{"airline": "Qatar Airways", 
"code":"QA",
"from":"Vancouver",
"to":"Dubai",
"date": "2023-09-28",
"fare": 950
}



### Update Flight
PUT http://localhost:5000/v1/flights/updateAFlight/63204e13720c07dd3e0d2fda
Content-Type: application/json

{"name": "Intercontenintal Hotel", 
"type":"hotel",
"city":"Kabul",
"address":"Bagh bala st",
"distance":"500",
"title": "Best Hotel",
"desc": "Hoteell",
"cheapestPrice": 100
}


### Delete a flight
DELETE http://localhost:8000/v1/flights/deleteAFlight/6328148e84557c0e9f7ee9ea
Content-Type: application/json



### Get a aflight by id
GET http://localhost:8000/v1/flights/getAFlight/6328148e84557c0e9f7ee9ea
Content-Type: application/json



### Get flights
GET http://localhost:8000/v1/flights/
Content-Type: application/json


### Search a flight by id
POST http://localhost:8000/v1/flights/searchAFlight
Content-Type: application/json

{
"from":"Dubai",
"to":"Vancouver",
"date": "2022-09-25"
}



//--------------------------------------------------------------------------------


### Create a new addUserDetail
POST http://localhost:8000/v1/userDetails/630c8f707740928186e01216
Content-Type: application/json

{
"firstName": "Sefatullah", 
"lastName": "Omar",
"birthdate": "1993-09-28",
"flights": "63280b9d153fee8f3309b332"
}



### get a loggedInUser UserDetails
GET http://localhost:8000/v1/userDetails/loggedInUser/630c8f707740928186e01216
Content-Type: application/json



### get a UserDetail
GET http://localhost:8000/v1/userDetails/632c3c91c7191d0ae902e8ec
Content-Type: application/json



### delete a UserDetail
Delete http://localhost:8000/v1/userDetails/632c05f8f0a597cbd9f7b897
Content-Type: application/json





# ----------------------------------------------------------------------
# Booking

### AddBooking.
POST http://localhost:8000/v1/bookings/
Content-Type: application/json

{
"bookedUser": "632c3c91c7191d0ae902e8ec",
"accountUser":"630c8f707740928186e01216",
"flight": "63280bec153fee8f3309b334",
"departureDate": "2022-10-30"
}


### Get a Booking for user
Get http://localhost:8000/v1/bookings/630c8f707740928186e01216
Content-Type: application/json


### Get a Booking based on bookingId
Get http://localhost:8000/v1/bookings/booking/19US11LS
Content-Type: application/json

W
### Get Booking.
Get http://localhost:8000/v1/bookings/
Content-Type: application/json


### Delte Booking.
Delete http://localhost:8000/v1/bookings/633d2b9766d6c8a64de92b9d/632852d623b5f98024289848
Content-Type: application/json




# ------------------------------------------------------------------------------
# ORDERS

### Delete an Order
DELETE http://localhost:8000/v1/flights/deleteAFlight/6328148e84557c0e9f7ee9ea
Content-Type: application/json



### Get an order by id
GET http://localhost:8000/v1/flights/getAFlight/6328148e84557c0e9f7ee9ea
Content-Type: application/json



### Get orders
GET http://localhost:8000/v1/orders/
Content-Type: application/json


### Get orders stats
GET http://localhost:8000/v1/orders/stats
Content-Type: application/json


### Get an order
GET http://localhost:8000/v1/orders/630c8f707740928186e01216
Content-Type: application/json



# ----------------------------------------------------------------------

###StripAPI
POST http://localhost:8000/v1/payments
Content-Type: application/json

{
"line_items": [
    {
        "quantity": 1,
        "price_data": {
        "currency": "usd",
        "unit_amount": 200,
        "product_data":{
            "name": "Airline Ticket",
            "description": "This is a one way aireline ticket"
        }
    }
    }
]
}


# --------------------------------------------------------------------------------------

###CreatePDF
POST http://localhost:8000/v1/create-pdf/
Content-Type: application/json

{

        "to":"Vancouver",
        "from":"Dubai",
        "airlines":"Emirate Airways",
        "firstName":"Sefatullah",
        "lastName":"Omar",
        "code": "EA",
        "date":"10/28/2022"
}